language: ruby
dist: focal
jobs:
  include:
    - rvm: 2.3.8
      before_install:
        - sudo apt-get update
        - rvm reinstall 2.3.8 --disable-binary
      install:
        - gem install bundler
        - bundle install
      script:
        - bundle exec rake spec
